# Generated by Django 5.0.2 on 2024-06-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_details', models.TextField()),
                ('profile_attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('contact_person_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('activities_since', models.DateField()),
                ('computer_forensics', models.BooleanField(default=False)),
                ('network_forensics', models.BooleanField(default=False)),
                ('mobile_devices_forensics', models.BooleanField(default=False)),
                ('digital_video_image_cctv_forensics', models.BooleanField(default=False)),
                ('digital_audio_forensics', models.BooleanField(default=False)),
                ('device_specific_forensics', models.BooleanField(default=False)),
                ('digital_equipment_machines', models.BooleanField(default=False)),
                ('any_other_forensics', models.CharField(blank=True, max_length=255, null=True)),
                ('detailed_description', models.TextField()),
                ('organization_chart', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('quality_manual', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('quality_manual_revision_date', models.DateField(blank=True, null=True)),
                ('quality_manual_details', models.TextField(blank=True, null=True)),
                ('sop_case_acceptance', models.BooleanField(default=False)),
                ('sop_handling_exhibits', models.BooleanField(default=False)),
                ('sop_security_preservation', models.BooleanField(default=False)),
                ('sop_analysis', models.BooleanField(default=False)),
                ('sop_report_format', models.BooleanField(default=False)),
                ('sop_tools_testing', models.BooleanField(default=False)),
                ('sop_training', models.BooleanField(default=False)),
                ('sop_internal_audit', models.BooleanField(default=False)),
                ('sop_other_procedures', models.TextField(blank=True, null=True)),
                ('lab_area', models.CharField(max_length=255)),
                ('fire_resistant_cupboards', models.IntegerField()),
                ('work_desks', models.IntegerField()),
                ('power_backup', models.TextField()),
                ('expert_opinions_last_three_years', models.IntegerField()),
            ],
        ),
    ]
