# Generated by Django 5.0.2 on 2024-06-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_form', '0006_alter_examinerapplication_user'),
    ]

    operations = [
    ]
