# Generated by Django 5.0.2 on 2024-07-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_form', '0008_alter_examinerapplication_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
    ]
