# Generated by Django 5.0.2 on 2024-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_form', '0009_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinerapplication',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
