# Generated by Django 5.0.2 on 2024-07-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_form', '0010_examinerapplication_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinerapplication',
            name='activities_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
